### ISSUE TITLE
MoaPanel : DataGrid 삽입 시 intrinsic width 오류 발생(콘솔)

### ISSUE THREAD

**Issue by bce0404** [midasit-dev/moaui#26]
![image](https://github.com/midasit-dev/moaui/assets/126432126/333a6bdc-0b47-41e5-99a6-eb0cca822cc6)

https://mui.com/x/react-data-grid/layout/

DataGrid를 MoaPanel으로 감싸는 경우, 위와 같은 오류가 콘솔에 표시됩니다.

MoaPanel의 layout 속성에서 다음 속성 두 개를 제거하는 경우 오류가 표시되지 않습니다.
```
display: 'flex',
flexDirection: 'column',
```

위 상황에서 width 속성도 동작하지 않는 것으로 보여 확인이 필요합니다.

**Comment by kh1012** [comment]
Panel Demo Test 동작에도 문제가 없어 말씀해주신 속성을 우선 삭제 했습니다.
마일스톤을 위해 PR 없이 dev 브랜치에 merge 진행 했습니다.
https://github.com/midasit-dev/moaui/commit/3d81eb31baefeae3ce1f63e941189c3c7ac55990
